//! endpoint:     notifications.notifications_count
//! flask path:   /notifications/count
//! axum path:    /notifications/count
//! method:       GET
//! source:       lib/api/v3/notifications/count_api.rb:11
//! handler_kind: ajax_json
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::State;
use axum::response::IntoResponse;

use crate::error::ApiResult;
use crate::extractors::{AppState, AuthenticatedUser, HalResponse};

pub async fn notifications_count(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
) -> ApiResult<impl IntoResponse> {
    let _ = state.pool()?;
    // CALIBRATION: build the response body from the Python source.
    // Output shape: ["unread", "total"]
    Ok(HalResponse(serde_json::json!({
        "_type": "NotificationsCount",
        "unread": serde_json::Value::Null,
        "total": serde_json::Value::Null,
        "_links": { "self": { "href": "/api/v3/notifications/count" } },
    })))
}
