//! endpoint:     work_packages.bulk_update_work_packages
//! flask path:   /work_packages/bulk
//! axum path:    /work_packages/bulk
//! method:       POST
//! source:       lib/api/v3/work_packages/bulk_api.rb:31
//! handler_kind: csrf_form_post_engine_call
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::State;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::Json;

use crate::error::ApiResult;
use crate::extractors::{AppState, AuthenticatedUser};

#[derive(Debug, serde::Deserialize)]
pub struct BulkUpdateWorkPackagesForm {
    pub ids: Option<String>,
    pub action: Option<String>,
}

pub async fn bulk_update_work_packages(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
    Json(form): Json<BulkUpdateWorkPackagesForm>,
) -> ApiResult<impl IntoResponse> {
    let _pool = state.pool()?;
    let _ = &form;
    // CALIBRATION: no model mapping for this form post; implement the engine
    // call against the Python source (the body invokes a service method, not a
    // direct model write). EXTRACTOR-GAP: add a [models.<Class>] entry to the
    // target spec, or extend the extractor if the model reference was missed.
    Ok(StatusCode::ACCEPTED)
}
