//! endpoint:     work_packages.create_work_package
//! flask path:   /projects/<int:project_id>/work_packages
//! axum path:    /projects/:project_id/work_packages
//! method:       POST
//! source:       lib/api/v3/work_packages/work_packages_api.rb:88
//! handler_kind: csrf_form_post_engine_call
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::Json;

use crate::error::{ApiError, ApiResult};
use crate::extractors::{AppState, AuthenticatedUser, HalResponse};
use crate::models::work_package::WorkPackage;

#[derive(Debug, serde::Deserialize)]
pub struct CreateWorkPackageForm {
    pub subject: Option<String>,
    pub description: Option<String>,
}

pub async fn create_work_package(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
    Path(project_id): Path<i64>,
    Json(form): Json<CreateWorkPackageForm>,
) -> ApiResult<impl IntoResponse> {
    let pool = state.pool()?;
    let created: WorkPackage = sqlx::query_as::<_, WorkPackage>(
        r#"INSERT INTO work_packages (project_id, subject, description) VALUES ($1, $2, $3) RETURNING *"#,
    )
    .bind(project_id)
    .bind(&form.subject)
    .bind(&form.description)
    .fetch_one(&pool)
    .await
    .map_err(|e| ApiError::internal(format!("Database error: {}", e)))?;

    Ok((StatusCode::CREATED, HalResponse(created)))
}
