//! endpoint:     projects.get_work_package
//! flask path:   /projects/<int:project_id>/work_packages/<int:id>
//! axum path:    /projects/:project_id/work_packages/:id
//! method:       GET
//! source:       lib/api/v3/projects/projects_api.rb:84
//! handler_kind: detail_for_tenant
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::{Path, State};
use axum::response::IntoResponse;

use crate::error::{ApiError, ApiResult};
use crate::extractors::{AppState, AuthenticatedUser, HalResponse};
use crate::models::work_package::WorkPackage;

pub async fn get_work_package(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
    Path((project_id, id)): Path<(i64, i64)>,
) -> ApiResult<impl IntoResponse> {
    let pool = state.pool()?;
    let item: WorkPackage = sqlx::query_as::<_, WorkPackage>(
        r#"SELECT * FROM work_packages WHERE id = $1 AND project_id = $2"#,
    )
    .bind(id)
    .bind(project_id)
    .fetch_optional(&pool)
    .await
    .map_err(|e| ApiError::internal(format!("Database error: {}", e)))?
    .ok_or_else(|| ApiError::not_found("WorkPackage", id))?;

    Ok(HalResponse(item))
}
