//! endpoint:     projects.list_work_packages
//! flask path:   /projects/<int:project_id>/work_packages
//! axum path:    /projects/:project_id/work_packages
//! method:       GET
//! source:       lib/api/v3/projects/projects_api.rb:42
//! handler_kind: list_for_tenant
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::{Path, State};
use axum::response::IntoResponse;

use crate::error::{ApiError, ApiResult};
use crate::extractors::{AppState, AuthenticatedUser, HalResponse, Pagination};
use crate::models::work_package::WorkPackage;

pub async fn list_work_packages(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
    Path(project_id): Path<i64>,
    pagination: Pagination,
) -> ApiResult<impl IntoResponse> {
    let pool = state.pool()?;
    let items: Vec<WorkPackage> = sqlx::query_as::<_, WorkPackage>(
        r#"SELECT * FROM work_packages WHERE project_id = $1 ORDER BY id DESC LIMIT $2 OFFSET $3"#,
    )
    .bind(project_id)
    .bind(pagination.page_size as i64)
    .bind(pagination.offset as i64)
    .fetch_all(&pool)
    .await
    .map_err(|e| ApiError::internal(format!("Database error: {}", e)))?;

    let total: i64 = sqlx::query_scalar::<_, i64>(
        r#"SELECT COUNT(*) FROM work_packages WHERE project_id = $1"#,
    )
    .bind(project_id)
    .fetch_one(&pool)
    .await
    .map_err(|e| ApiError::internal(format!("Database error: {}", e)))?;

    Ok(HalResponse(serde_json::json!({
        "_type": "Collection",
        "total": total,
        "count": items.len(),
        "pageSize": pagination.page_size,
        "offset": pagination.offset,
        "_embedded": { "elements": items },
    })))
}
