//! endpoint:     projects.archive_work_package
//! flask path:   /projects/<int:project_id>/work_packages/<int:id>/archive
//! axum path:    /projects/:project_id/work_packages/:id/archive
//! method:       POST
//! source:       lib/api/v3/projects/projects_api.rb:120
//! handler_kind: soft_delete
//! scoping:      login_required
//
// GENERATED by ruff_python_codegen — DO NOT EDIT.
// Modify target-spec/openproject-axum-sqlx.toml instead.

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::IntoResponse;

use crate::error::{ApiError, ApiResult};
use crate::extractors::{AppState, AuthenticatedUser};

pub async fn archive_work_package(
    State(state): State<AppState>,
    _user: AuthenticatedUser,
    Path((project_id, id)): Path<(i64, i64)>,
) -> ApiResult<impl IntoResponse> {
    let pool = state.pool()?;
    let rows = sqlx::query(
        r#"UPDATE work_packages SET active = false WHERE id = $1 AND project_id = $2 AND active = true"#,
    )
    .bind(id)
    .bind(project_id)
    .execute(&pool)
    .await
    .map_err(|e| ApiError::internal(format!("Database error: {}", e)))?
    .rows_affected();

    if rows == 0 {
        return Err(ApiError::not_found("WorkPackage", id));
    }
    Ok(StatusCode::NO_CONTENT)
}
