//! sqlx (axum + raw `sqlx::query_as`) emitter for the
//! [`HandlerKind::AjaxJson`] kind.
//!
//! AjaxJson is the generic JSON-return classification — it fires when the
//! body's response is `jsonify(...)` and the route isn't a tenant-scoped
//! list or detail. Roughly 25% of OpenProject's v3 actions land here. The
//! shape divides cleanly in two:
//!
//! 1. **With a resolvable primary model**: query the model by primary key
//!    (no tenant filter — that's the [`HandlerKind::DetailForTenant`]
//!    sibling) and wrap the row in a HAL envelope (`_type` + `_embedded`
//!    + `_links`).
//! 2. **Without a resolvable model** (e.g. `/api/v3/notifications/count`):
//!    emit a documented stub — `CALIBRATION` comment + `serde_json::Value::Null`
//!    placeholders for each key in `contract.output`'s `Json { shape }`.
//!
//! The shape is byte-faithful to the openproject-axum-sqlx target goldens
//! at `tests/golden/codegen/sqlx/expected/ajax_json_{with_model,stub}.rs`
//! so the integration test trims output and compares it to the expected
//! files.
//!
//! Inert until the orchestrator wires `pub mod ajax_json;` into the parent
//! `sqlx_emit` module — the file is self-contained and pulls no private
//! helpers from `codegen::mod`.
//!
//! ## Primary-key policy
//!
//! Unlike [`HandlerKind::DetailForTenant`] the AjaxJson kind does not need
//! to thread a tenant scope; the primary key is taken from the *first*
//! path parameter (the one that conventionally identifies the resource
//! along the family axis, e.g. `user_id` on `/users/<int:user_id>/...`).
//! When no path params are present, the with-model branch is unreachable
//! by construction — the stub branch handles the parameter-less shape.

use std::fmt::Write as _;

use crate::codegen::Emitted;
use crate::codegen::target::TargetSpec;
use crate::contract::{PathParam, RouteContract};
use crate::extractors::body::OutputKind;

/// Emit a sqlx (axum + `sqlx::query_as`) AjaxJson handler for one route
/// contract against `spec`. The output is a complete, compileable Rust
/// file under the caller's choice of `handler_file` name; when no primary
/// model can be resolved against the spec, the handler is replaced with a
/// documented `CALIBRATION` stub that returns a HAL envelope of
/// `serde_json::Value::Null` placeholders (Iron Rule 1: never emit
/// `todo!()`/`unimplemented!()` into a compilable production path).
pub fn emit_ajax_json_sqlx(contract: &RouteContract, spec: &TargetSpec) -> Emitted {
    let fn_name = &contract.function;
    let axum = axum_path(&contract.path);
    let scoping = if contract.guards.is_empty() {
        "none".to_string()
    } else {
        contract.guards.join(", ")
    };

    let header = format!(
        "//! endpoint:     {endpoint}\n\
         //! flask path:   {flask}\n\
         //! axum path:    {axum}\n\
         //! method:       {method}\n\
         //! source:       {file}:{line}\n\
         //! handler_kind: ajax_json\n\
         //! scoping:      {scoping}\n\
         //\n\
         // GENERATED by ruff_python_codegen — DO NOT EDIT.\n\
         // Modify target-spec/openproject-axum-sqlx.toml instead.\n",
        endpoint = contract.id,
        flask = contract.path,
        method = contract.methods.join(","),
        file = contract.provenance.file,
        line = contract.provenance.line_start,
    );

    let (referenced_models, body) = match primary_model(contract, spec) {
        Some((py_class, module_path)) => {
            // Build the model struct path inline. The sqlx target does NOT
            // append `::Model` (that suffix is seaorm-specific); the struct
            // *is* the row type implementing `FromRow`.
            let model_struct = format!("{}::{}::{py_class}", spec.models_root, module_path);
            let table = pluralize_snake(py_class);

            let params: &[PathParam] = &contract.inputs.path_params;
            let primary_name = primary_param_name(params);
            let path_extractor = path_extractor(params);
            let family = &contract.family;

            let body = format!(
                "\n\
                 use axum::extract::{{Path, State}};\n\
                 use axum::response::IntoResponse;\n\
                 \n\
                 use crate::error::{{ApiError, ApiResult}};\n\
                 use crate::extractors::{{AppState, AuthenticatedUser, HalResponse}};\n\
                 use {model_struct};\n\
                 \n\
                 pub async fn {fn_name}(\n\
                 \x20   State(state): State<AppState>,\n\
                 \x20   _user: AuthenticatedUser,\n\
                 \x20   {path_extractor},\n\
                 ) -> ApiResult<impl IntoResponse> {{\n\
                 \x20   let pool = state.pool()?;\n\
                 \x20   let item: {py_class} = sqlx::query_as::<_, {py_class}>(\n\
                 \x20       r#\"SELECT * FROM {table} WHERE id = $1\"#,\n\
                 \x20   )\n\
                 \x20   .bind({primary_name})\n\
                 \x20   .fetch_optional(&pool)\n\
                 \x20   .await\n\
                 \x20   .map_err(|e| ApiError::internal(format!(\"Database error: {{}}\", e)))?\n\
                 \x20   .ok_or_else(|| ApiError::not_found(\"{py_class}\", {primary_name}))?;\n\
                 \n\
                 \x20   Ok(HalResponse(serde_json::json!({{\n\
                 \x20       \"_type\": \"{py_class}\",\n\
                 \x20       \"_embedded\": item,\n\
                 \x20       \"_links\": {{ \"self\": {{ \"href\": format!(\"/api/v3/{family}/{{}}\", {primary_name}) }} }},\n\
                 \x20   }})))\n\
                 }}\n",
            );
            (vec![py_class.to_string()], body)
        }
        None => {
            let type_name = to_pascal(&contract.function);
            let shape = json_shape(&contract.output);
            let shape_comment = format_shape_comment(&shape);
            let null_lines = format_null_placeholders(&shape);
            let self_href = format!("/api/v3{}", contract.path);

            let body = format!(
                "\n\
                 use axum::extract::State;\n\
                 use axum::response::IntoResponse;\n\
                 \n\
                 use crate::error::ApiResult;\n\
                 use crate::extractors::{{AppState, AuthenticatedUser, HalResponse}};\n\
                 \n\
                 pub async fn {fn_name}(\n\
                 \x20   State(state): State<AppState>,\n\
                 \x20   _user: AuthenticatedUser,\n\
                 ) -> ApiResult<impl IntoResponse> {{\n\
                 \x20   let _ = state.pool()?;\n\
                 \x20   // CALIBRATION: build the response body from the Python source.\n\
                 \x20   // Output shape: {shape_comment}\n\
                 \x20   Ok(HalResponse(serde_json::json!({{\n\
                 \x20       \"_type\": \"{type_name}\",\n\
                 {null_lines}\
                 \x20       \"_links\": {{ \"self\": {{ \"href\": \"{self_href}\" }} }},\n\
                 \x20   }})))\n\
                 }}\n",
            );
            (contract.data.models.clone(), body)
        }
    };

    Emitted {
        handler_rs: format!("{header}{body}"),
        view_html: None,
        handler_file: format!("{}__{}.rs", contract.family, fn_name),
        view_file: None,
        referenced_models,
        provided_context_keys: Vec::new(),
    }
}

/// Flask `<int:foo>` / `<foo>` → axum `:foo`. Mirrors the helper in
/// `codegen::mod` (private there); inlined to keep this module
/// self-contained — see the file-level doc-comment.
fn axum_path(flask_path: &str) -> String {
    let mut out = String::with_capacity(flask_path.len());
    let mut rest = flask_path;
    while let Some(open) = rest.find('<') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        let Some(close) = after.find('>') else {
            out.push_str(&rest[open..]);
            return out;
        };
        let inner = &after[..close];
        let name = inner.split_once(':').map_or(inner, |(_, n)| n);
        out.push(':');
        out.push_str(name);
        rest = &after[close + 1..];
    }
    out.push_str(rest);
    out
}

/// Resolve the first mapped model in `contract.data.models`. Returns
/// `(python_class, module_path)` — the python class is kept verbatim so the
/// generated sqlx struct reference is `crate::models::<module>::<Class>`
/// (the sqlx target does NOT append `::Model`; that suffix is seaorm-only).
fn primary_model<'a>(
    contract: &'a RouteContract,
    spec: &'a TargetSpec,
) -> Option<(&'a str, &'a str)> {
    for m in &contract.data.models {
        if let Some((k, v)) = spec.models.get_key_value(m) {
            return Some((k.as_str(), v.module_path.as_str()));
        }
    }
    None
}

/// Map a Flask path converter to the sqlx-bind Rust type. The sqlx target
/// uses `i64` (Postgres `BIGINT`) for integers — matches the
/// [`detail_for_tenant`] sibling so emitted handlers compose across kinds.
fn flask_conv_to_sqlx_rust(converter: Option<&str>) -> &'static str {
    match converter {
        Some("int") => "i64",
        Some("float") => "f64",
        _ => "String",
    }
}

/// Build the `Path(...)` extractor line. For AjaxJson with a resolvable
/// model we always have at least one path param (the resource id); the 0
/// case is handled by the stub branch and never reaches this helper.
fn path_extractor(params: &[PathParam]) -> String {
    match params {
        [] => "Path(_): Path<()>".to_string(),
        [p] => format!(
            "Path({}): Path<{}>",
            p.name,
            flask_conv_to_sqlx_rust(p.converter.as_deref())
        ),
        many => {
            let names = many
                .iter()
                .map(|p| p.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let tys = many
                .iter()
                .map(|p| flask_conv_to_sqlx_rust(p.converter.as_deref()))
                .collect::<Vec<_>>()
                .join(", ");
            format!("Path(({names})): Path<({tys})>")
        }
    }
}

/// The primary key on an AjaxJson route is conventionally the **first**
/// path parameter — the family-axis identifier (e.g. `user_id` on
/// `/users/<int:user_id>/preferences`). Falls back to `id` for the
/// degenerate no-param case so the emitted code still compiles.
fn primary_param_name(params: &[PathParam]) -> &str {
    params.first().map_or("id", |p| p.name.as_str())
}

/// `WorkPackage` → `work_packages`, `User` → `users`. Naïve snake_case +
/// `s` suffix; mirrors the [`detail_for_tenant`] sibling.
fn pluralize_snake(class: &str) -> String {
    let snake = to_snake_case(class);
    if snake.ends_with('s') {
        snake
    } else {
        format!("{snake}s")
    }
}

fn to_snake_case(class: &str) -> String {
    let mut out = String::with_capacity(class.len() + 4);
    for (i, ch) in class.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// `notifications_count` → `NotificationsCount`. Underscores are treated as
/// word boundaries; each segment is title-cased and concatenated. Used to
/// build the `_type` field for the stub branch (which has no resolvable
/// model class to borrow).
fn to_pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for part in s.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

/// Extract the `Json { shape }` keys; empty for any other `OutputKind`.
fn json_shape(output: &OutputKind) -> Vec<String> {
    match output {
        OutputKind::Json { shape } => shape.clone(),
        _ => Vec::new(),
    }
}

/// Render the shape as a Rust-array-literal comment: `["unread", "total"]`.
fn format_shape_comment(shape: &[String]) -> String {
    let mut out = String::from("[");
    for (i, k) in shape.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let _ = write!(out, "\"{k}\"");
    }
    out.push(']');
    out
}

/// Render one `serde_json::Value::Null` placeholder per shape key, each
/// line with its own indent and trailing newline ready to splice into the
/// `json!` macro body.
fn format_null_placeholders(shape: &[String]) -> String {
    let mut out = String::new();
    for k in shape {
        let _ = writeln!(out, "        \"{k}\": serde_json::Value::Null,");
    }
    out
}
