//! sqlx variant of the `soft_delete` emitter.
//!
//! Mirrors the shape of [`crate::codegen::emit_soft_delete`] (see
//! `codegen/mod.rs:437`) but targets an API-first axum + plain `sqlx::query`
//! handler instead of the seaorm + server-rendered redirect flavor. The
//! generated handler runs a single `UPDATE … SET active = false` against the
//! pool and returns `204 No Content` (or `ApiError::not_found` when the row
//! is already inactive or missing).
//!
//! This module is intentionally inert: it is only reachable once the codegen
//! orchestrator wires `sqlx_emit::soft_delete::emit_soft_delete_sqlx` into the
//! `KindRecipe` dispatcher for the openproject-axum-sqlx target.

use std::fmt::Write as _;

use crate::codegen::target::TargetSpec;
use crate::codegen::Emitted;
use crate::contract::{PathParam, RouteContract};

/// Emit a 204-style sqlx soft-delete handler for `contract` against `spec`.
///
/// The generated handler shape (verified against
/// `tests/golden/codegen/sqlx/expected/soft_delete.rs`):
///
/// * extracts `(State, AuthenticatedUser, Path<(..)>)`;
/// * runs `UPDATE <table> SET active = false WHERE id = $1 AND
///   <scope> = $2 AND active = true` so only currently-active rows flip;
/// * returns `Err(ApiError::not_found(<Class>, id))` when `rows_affected == 0`
///   (covers both "already inactive" and "doesn't exist");
/// * returns `Ok(StatusCode::NO_CONTENT)` otherwise — the openproject API-first
///   convention, vs the seaorm emitter's `Redirect` (which targets a
///   server-rendered web app).
pub fn emit_soft_delete_sqlx(contract: &RouteContract, spec: &TargetSpec) -> Emitted {
    let _ = spec;

    let fn_name = contract.function.clone();
    let axum = axum_path(&contract.path);

    let primary_class = contract
        .data
        .models
        .first()
        .cloned()
        .unwrap_or_else(|| "Row".to_string());
    let table = pluralize_snake(&primary_class);

    // The primary key parameter is the *last* path param (e.g.
    // `/projects/<project_id>/work_packages/<id>/archive` ⇒ `id`); the
    // earlier params are the tenant/owner scope (`project_id`).
    let params: &[PathParam] = &contract.inputs.path_params;
    let (primary_name, scope_params) = split_primary_and_scope(params);

    let path_extractor = path_extractor(params);
    let where_clause = where_clause(primary_name, scope_params);
    let bindings = bind_lines(primary_name, scope_params);

    let header = format!(
        "//! endpoint:     {endpoint}\n\
         //! flask path:   {flask}\n\
         //! axum path:    {axum}\n\
         //! method:       {methods}\n\
         //! source:       {file}:{line}\n\
         //! handler_kind: soft_delete\n\
         //! scoping:      {guards}\n\
         //\n\
         // GENERATED by ruff_python_codegen — DO NOT EDIT.\n\
         // Modify target-spec/openproject-axum-sqlx.toml instead.\n",
        endpoint = contract.id,
        flask = contract.path,
        methods = contract.methods.join(","),
        file = contract.provenance.file,
        line = contract.provenance.line_start,
        guards = if contract.guards.is_empty() {
            "none".to_string()
        } else {
            contract.guards.join(", ")
        },
    );

    let imports = "\n\
        use axum::extract::{Path, State};\n\
        use axum::http::StatusCode;\n\
        use axum::response::IntoResponse;\n\
        \n\
        use crate::error::{ApiError, ApiResult};\n\
        use crate::extractors::{AppState, AuthenticatedUser};\n";

    let mut body = String::new();
    let _ = writeln!(body);
    let _ = writeln!(body, "pub async fn {fn_name}(");
    let _ = writeln!(body, "    State(state): State<AppState>,");
    let _ = writeln!(body, "    _user: AuthenticatedUser,");
    let _ = writeln!(body, "    {path_extractor},");
    let _ = writeln!(body, ") -> ApiResult<impl IntoResponse> {{");
    let _ = writeln!(body, "    let pool = state.pool()?;");
    let _ = writeln!(body, "    let rows = sqlx::query(");
    let _ = writeln!(
        body,
        "        r#\"UPDATE {table} SET active = false WHERE {where_clause}\"#,"
    );
    let _ = writeln!(body, "    )");
    body.push_str(&bindings);
    let _ = writeln!(body, "    .execute(&pool)");
    let _ = writeln!(body, "    .await");
    let _ = writeln!(
        body,
        "    .map_err(|e| ApiError::internal(format!(\"Database error: {{}}\", e)))?"
    );
    let _ = writeln!(body, "    .rows_affected();");
    let _ = writeln!(body);
    let _ = writeln!(body, "    if rows == 0 {{");
    let _ = writeln!(
        body,
        "        return Err(ApiError::not_found(\"{primary_class}\", {primary_name}));"
    );
    let _ = writeln!(body, "    }}");
    let _ = writeln!(body, "    Ok(StatusCode::NO_CONTENT)");
    let _ = writeln!(body, "}}");

    let handler_rs = format!("{header}{imports}{body}");

    Emitted {
        handler_rs,
        view_html: None,
        handler_file: format!("{}__{}.rs", contract.family, contract.function),
        view_file: None,
        referenced_models: vec![primary_class],
        provided_context_keys: Vec::new(),
    }
}

/// Translate a Flask URL pattern to an axum-style pattern. Mirrors the helper
/// in `codegen/mod.rs:138` so the emitted header matches the seaorm one
/// character-for-character on the shared lines.
fn axum_path(flask_path: &str) -> String {
    let mut out = String::with_capacity(flask_path.len());
    let mut rest = flask_path;
    while let Some(open) = rest.find('<') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        let Some(close) = after.find('>') else {
            out.push_str(&rest[open..]);
            return out;
        };
        let inner = &after[..close];
        let name = inner.split_once(':').map_or(inner, |(_, n)| n);
        out.push(':');
        out.push_str(name);
        rest = &after[close + 1..];
    }
    out.push_str(rest);
    out
}

/// Map a Flask path converter to the sqlx-bind Rust type. The sqlx target
/// uses `i64` (Postgres `BIGINT`) for integers — distinct from the seaorm
/// emitter which uses `i32`.
fn flask_conv_to_sqlx_rust(converter: Option<&str>) -> &'static str {
    match converter {
        Some("int") => "i64",
        Some("float") => "f64",
        _ => "String",
    }
}

/// Build the `Path(...)` extractor line (zero/one/many params).
fn path_extractor(params: &[PathParam]) -> String {
    match params {
        [] => "Path(_): Path<()>".to_string(),
        [p] => format!(
            "Path({}): Path<{}>",
            p.name,
            flask_conv_to_sqlx_rust(p.converter.as_deref())
        ),
        many => {
            let names = many
                .iter()
                .map(|p| p.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let tys = many
                .iter()
                .map(|p| flask_conv_to_sqlx_rust(p.converter.as_deref()))
                .collect::<Vec<_>>()
                .join(", ");
            format!("Path(({names})): Path<({tys})>")
        }
    }
}

/// The primary key is conventionally the *last* path parameter on a
/// soft-delete route (`/<scope>/<id>/archive`). When no path params are
/// present, fall back to `id` so the emitted code still compiles.
fn split_primary_and_scope(params: &[PathParam]) -> (&str, &[PathParam]) {
    match params.split_last() {
        Some((last, rest)) => (last.name.as_str(), rest),
        None => ("id", &[]),
    }
}

/// Build the SQL `WHERE` clause: `id = $1 [AND <scope> = $N]* AND active = true`.
fn where_clause(primary_name: &str, scope_params: &[PathParam]) -> String {
    let mut out = format!("{primary_name} = $1");
    for (idx, p) in scope_params.iter().enumerate() {
        let _ = write!(out, " AND {} = ${}", p.name, idx + 2);
    }
    out.push_str(" AND active = true");
    out
}

/// Build the `.bind(...)` lines in `$1, $2, …` order (primary first, then
/// scope params in URL order).
fn bind_lines(primary_name: &str, scope_params: &[PathParam]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "    .bind({primary_name})");
    for p in scope_params {
        let _ = writeln!(out, "    .bind({})", p.name);
    }
    out
}

/// `WorkPackage` → `work_packages`, `Customer` → `customers`. Naïve
/// snake_case + `s` suffix, sufficient for the contract surface this emitter
/// targets (the spec deliberately keeps the mapping inline; a full
/// inflector lives in the orchestrator).
fn pluralize_snake(class: &str) -> String {
    let snake = to_snake_case(class);
    if snake.ends_with('s') {
        snake
    } else {
        format!("{snake}s")
    }
}

fn to_snake_case(class: &str) -> String {
    let mut out = String::with_capacity(class.len() + 4);
    for (i, ch) in class.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
