//! sqlx emitter for the `toggle_bool_field` handler kind.
//!
//! Sister to `crate::codegen::emit_toggle_bool_field` (sea-orm). The sqlx
//! variant flips the bool atomically via `UPDATE ... SET active = NOT active
//! WHERE id = $1 AND <scope> = $2 RETURNING *`, maps a missing row to a
//! `404`, and returns the updated resource as HAL JSON. Self-contained: no
//! shared helpers are imported, so this file can be wired in by the
//! orchestrator without touching `mod.rs`.
//!
//! The function is currently inert — it is not referenced from the codegen
//! dispatcher until the orchestrator wires the sqlx target.

use crate::codegen::Emitted;
use crate::codegen::target::TargetSpec;
use crate::contract::{PathParam, RouteContract};

/// Emit a sqlx handler that flips a single bool column on a tenant-scoped row
/// and returns the updated resource as HAL JSON. Mirrors the sea-orm
/// `emit_toggle_bool_field` shape but uses raw SQL + `sqlx::query_as` instead
/// of an `ActiveModel` round-trip.
pub fn emit_toggle_bool_field_sqlx(contract: &RouteContract, spec: &TargetSpec) -> Emitted {
    let fn_name = &contract.function;
    let axum = axum_path(&contract.path);

    let (referenced_models, body) = match primary_model(contract, spec) {
        Some((py_class, module_path)) => {
            let class = py_class.to_string();
            let model_use = format!("{root}::{}::{class}", module_path, root = spec.models_root);
            let table = table_name(&class);
            let path_extractor = path_extractor(&contract.inputs.path_params);
            let scope_col = scope_column(contract);
            let (sql, binds) = update_sql_and_binds(&table, &scope_col);

            let block = format!(
                "use axum::extract::{{Path, State}};\n\
                 use axum::response::IntoResponse;\n\
                 \n\
                 use crate::error::{{ApiError, ApiResult}};\n\
                 use crate::extractors::{{AppState, AuthenticatedUser, HalResponse}};\n\
                 use {model_use};\n\
                 \n\
                 pub async fn {fn_name}(\n\
                 \x20   State(state): State<AppState>,\n\
                 \x20   _user: AuthenticatedUser,\n\
                 {path_extractor}\
                 ) -> ApiResult<impl IntoResponse> {{\n\
                 \x20   let pool = state.pool()?;\n\
                 \x20   let updated: {class} = sqlx::query_as::<_, {class}>(\n\
                 \x20       r#\"{sql}\"#,\n\
                 \x20   )\n\
                 {binds}\
                 \x20   .fetch_optional(&pool)\n\
                 \x20   .await\n\
                 \x20   .map_err(|e| ApiError::internal(format!(\"Database error: {{}}\", e)))?\n\
                 \x20   .ok_or_else(|| ApiError::not_found(\"{class}\", id))?;\n\
                 \n\
                 \x20   Ok(HalResponse(updated))\n\
                 }}\n",
            );
            let _ = axum; // axum route shape is encoded in the header only.
            (vec![class], block)
        }
        None => (contract.data.models.clone(), unresolved_block(contract, spec)),
    };

    let header = sqlx_header(contract, &axum);
    Emitted {
        handler_rs: format!("{header}{body}"),
        view_html: None,
        handler_file: format!("{}__{}.rs", contract.family, fn_name),
        view_file: None,
        referenced_models,
        provided_context_keys: Vec::new(),
    }
}

/// Render the file-level header doc block exactly like the sqlx goldens
/// (`endpoint`, `flask path`, `axum path`, `method`, `source`, `handler_kind`,
/// `scoping`), followed by the boilerplate generated-by banner.
fn sqlx_header(contract: &RouteContract, axum: &str) -> String {
    let endpoint = &contract.id;
    let flask = &contract.path;
    let method = contract.methods.first().cloned().unwrap_or_default();
    let file = &contract.provenance.file;
    let line = contract.provenance.line_start;
    let scoping = if contract.guards.is_empty() {
        "none".to_string()
    } else {
        contract.guards.join(", ")
    };
    format!(
        "//! endpoint:     {endpoint}\n\
         //! flask path:   {flask}\n\
         //! axum path:    {axum}\n\
         //! method:       {method}\n\
         //! source:       {file}:{line}\n\
         //! handler_kind: toggle_bool_field\n\
         //! scoping:      {scoping}\n\
         //\n\
         // GENERATED by ruff_python_codegen — DO NOT EDIT.\n\
         // Modify target-spec/openproject-axum-sqlx.toml instead.\n\
         \n",
    )
}

/// Honest stub when the primary model has no spec mapping: emit a documented
/// `compile_error!` so the missing mapping is visible at the consumer side
/// rather than producing wrong code (Iron Rule: no silent fallback).
fn unresolved_block(contract: &RouteContract, spec: &TargetSpec) -> String {
    let models = contract.data.models.join(", ");
    format!(
        "// Unresolved primary model for sqlx target `{target}`.\n\
         // Observed models: [{models}]. Add a `[models.<Class>]` entry to the\n\
         // target-spec TOML so the emitter can resolve a module path.\n\
         compile_error!(\"sqlx toggle_bool_field: no model mapping for `{models}`\");\n",
        target = spec.id,
    )
}

/// Build the `Path(...)` extractor line. 0 params → empty; 1 → `Path(name)`;
/// 2+ → tuple-destructured `Path((a, b, ...))` with `i64` per int converter
/// and `String` otherwise. Trailing newline + 4-space indent included so the
/// caller can splice into a function signature directly.
fn path_extractor(params: &[PathParam]) -> String {
    if params.is_empty() {
        return String::new();
    }
    if params.len() == 1 {
        let p = &params[0];
        let ty = rust_ty(p);
        return format!("    Path({name}): Path<{ty}>,\n", name = p.name);
    }
    let names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
    let tys: Vec<String> = params.iter().map(rust_ty).collect();
    format!(
        "    Path(({names_csv})): Path<({tys_csv})>,\n",
        names_csv = names.join(", "),
        tys_csv = tys.join(", "),
    )
}

/// Map a path-param converter to its Rust extractor type. `int` → `i64`,
/// `float` → `f64`, everything else (`string`/`path`/`uuid`/`None`) → `String`.
fn rust_ty(p: &PathParam) -> String {
    match p.converter.as_deref() {
        Some("int") => "i64".to_string(),
        Some("float") => "f64".to_string(),
        _ => "String".to_string(),
    }
}

/// Resolve the primary model: first contract model with a target mapping.
/// Returns `(python_class, module_path)` — the caller composes the full
/// `crate::models::<module>::<Class>` import path itself, per the file's
/// "build the model struct path inline" hard rule.
fn primary_model<'a>(contract: &'a RouteContract, spec: &'a TargetSpec) -> Option<(&'a str, &'a str)> {
    for m in &contract.data.models {
        if let Some(mapping) = spec.resolve_model(m) {
            return Some((m.as_str(), mapping.module_path.as_str()));
        }
    }
    None
}

/// Snake_case + naive English plural of a PascalCase class.
///
/// `WorkPackage` → `work_packages`; `Activity` → `activities`; `Address` →
/// `addresses`. Sufficient for the openproject domain's model names.
fn table_name(class: &str) -> String {
    pluralize(&pascal_to_snake(class))
}

fn pascal_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn pluralize(s: &str) -> String {
    if s.ends_with('y') && !ends_with_vowel_y(s) {
        format!("{}ies", &s[..s.len() - 1])
    } else if s.ends_with('s') || s.ends_with('x') || s.ends_with("ch") || s.ends_with("sh") {
        format!("{s}es")
    } else {
        format!("{s}s")
    }
}

fn ends_with_vowel_y(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.len() < 2 {
        return false;
    }
    matches!(bytes[bytes.len() - 2], b'a' | b'e' | b'i' | b'o' | b'u')
}

/// Pick the tenant/parent scope column from the path params (the first param
/// that is not the primary `id`). Snake_case is preserved verbatim from the
/// Flask converter name, so `project_id` stays `project_id`.
fn scope_column(contract: &RouteContract) -> Option<String> {
    contract
        .inputs
        .path_params
        .iter()
        .find(|p| p.name != "id")
        .map(|p| p.name.clone())
}

/// Compose the `UPDATE ... SET active = NOT active WHERE ... RETURNING *`
/// statement plus the `.bind(...)` chain (primary `id` first, then optional
/// scope param). The two are returned together so the caller doesn't have to
/// re-derive bind order from the SQL.
fn update_sql_and_binds(table: &str, scope: &Option<String>) -> (String, String) {
    match scope {
        Some(col) => {
            let sql = format!(
                "UPDATE {table} SET active = NOT active WHERE id = $1 AND {col} = $2 RETURNING *",
            );
            let binds = "    .bind(id)\n    .bind(".to_string() + col + ")\n";
            (sql, binds)
        }
        None => {
            let sql = format!("UPDATE {table} SET active = NOT active WHERE id = $1 RETURNING *");
            let binds = "    .bind(id)\n".to_string();
            (sql, binds)
        }
    }
}

// ---------------------------------------------------------------------------
// Local copy of the Flask→axum path translator. Kept inline so this module is
// self-contained per the wiring brief; the sister sea-orm emitter has its own
// copy under the same name in `codegen::mod`.
// ---------------------------------------------------------------------------

fn axum_path(flask_path: &str) -> String {
    let mut out = String::with_capacity(flask_path.len());
    let mut rest = flask_path;
    while let Some(open) = rest.find('<') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        let Some(close) = after.find('>') else {
            out.push_str(&rest[open..]);
            return out;
        };
        let inner = &after[..close];
        let name = inner.split_once(':').map_or(inner, |(_, n)| n);
        out.push(':');
        out.push_str(name);
        rest = &after[close + 1..];
    }
    out.push_str(rest);
    out
}
